apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: enriq-controlplane
spec:
  profile: demo
  components:
    pilot:
      k8s:
        resources:
          requests:
            memory: 2048Mi
    egressGateways:
      - name: istio-egress